site_name: Simple Static Site
site_url: https://akrafts.github.io/simple-static-site/
theme:
  name: material
nav:
  - Home: index.md
  - About: about/index.md
  - Aerolink: aerolink/index.md
  - Ambient: ambient/index.md
  - Contact: contact/index.md
  - Echo: echo/index.md
  - Fly: fly/index.md
  - Gourmet: gourmet/index.md
  - Maps:
      - Overview: maps/index.md
      - Why: maps/why/index.md
      - When: maps/when/index.md
      - PDF: maps/pdf/index.md
      - Wild: maps/wild/index.md
      - Next: maps/next/index.md
      - Curate: maps/curate/index.md
      - Price: maps/price/index.md
      - Fly: maps/fly/index.md
      - Time: maps/time/index.md
      - AI: maps/ai/index.md
  - Personal Virtual Embassy: personal_virtual_embassy/index.md
  - Tribe to Fly: tribe-to-fly/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
